### ISSUE TITLE
Create TensorFlow Kafka-based Queue Reader/Feeder 

### ISSUE THREAD

**Issue by cfregly** [PipelineAI/pipeline#115]
https://www.tensorflow.org/versions/r0.10/how_tos/threading_and_queues/index.html

https://www.tensorflow.org/versions/r0.10/how_tos/reading_data/index.html

https://www.tensorflow.org/versions/r0.10/api_docs/python/io_ops.html

https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/examples/how_tos/reading_data/convert_to_records.py

**Comment by cfregly** [comment]
https://indico.io/blog/tensorflow-data-inputs-part1-placeholders-protobufs-queues/

https://indico.io/blog/tensorflow-data-input-part2-extensions/

**Comment by cfregly** [comment]
Consider co-location of the TF training code with the Kafka data partitions to improve data locality and reduce data movement across the network.  May be difficult to achieve locality between these 2 systems, but worth investigating.

**Comment by samjabrahams** [comment]
Eventually, I think we'll want to create our own TensorFlow Queue for easy pre-fetching of data, but we can wrap the Kafka Python calls with this in the meantime

https://www.tensorflow.org/versions/master/api_docs/python/script_ops.html#py_func

**Comment by cfregly** [comment]
example of tfrecordwriter/reader:  https://www.tensorflow.org/versions/r0.11/api_docs/python/python_io.html#data-io-python-functions

**Comment by cfregly** [comment]
another example of tfrecordwriter/reader:  https://github.com/amygdala/tensorflow-workshop/blob/541d4793b93bae0372a5f3569a1d4d549aa1255a/workshop_sections/mnist_series/cloudml/trainer/util.py

**Comment by cfregly** [comment]
recommended workflow:  read data from binary, process (ie. csv processing or filtering), write back out as binary.  basically, keep as binary for as long as possible!

**Comment by cfregly** [comment]
tf.train.Example and tf.train.Feature are python bindings for protobuf given to us for free from tensorflow

**Comment by cfregly** [comment]
End-to-end example:  https://github.com/amygdala/tensorflow-workshop/tree/master/workshop_sections/mnist_series/cloudml

**Comment by cfregly** [comment]
kafka + protobuf:  https://gist.github.com/ezsi/153ff1b661198e21e7d9

**Comment by cfregly** [comment]
reverse-engineer this:  https://github.com/amygdala/tensorflow-workshop/blob/master/workshop_sections/mnist_series/cloudml/README.md
