### ISSUE TITLE
Setup JupyterHub on Kubernetes Cluster to Spawn Separate Docker Container for each User that logs in

### ISSUE THREAD

**Issue by cfregly** [PipelineAI/pipeline#120]
https://github.com/jupyterhub/jupyterhub-deploy-docker

**Comment by cfregly** [comment]
Dummy authenticator for testing
https://github.com/yuvipanda/jupyterhub-dummy-authenticator

**Comment by cfregly** [comment]
kubernetes spawned

https://github.com/yuvipanda/jupyterhub-kubernetes-spawner/blob/master/kubespawner/spawner.py

**Comment by cfregly** [comment]
https://github.com/GoogleCloudPlatform/gke-jupyter-classroom

**Comment by cfregly** [comment]
ok, here is the summary:

Follow this guide:  https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/

which references this Helm Chart:  https://github.com/jupyterhub/helm-chart

you should use Minikube locally on your laptop to prototype this - we *shouldn't* need a real kuberentes cluster, but get as far as you can and lemme know if you get stuck.

here's some other resources that may be interesting, but might also be a distraction: 

https://github.com/GoogleCloudPlatform/gke-jupyter-classroom
https://github.com/odewahn/jupyterhub-on-gcloud

don't worry about authentication.  just get the end-to-end working.  there's a LOT of work just getting the end-to-end working.

**Comment by saulshanabrook** [comment]
@cfregly This sounds good! I'll start on this tomorrow. I had this as a TODO for my Hampshire lab anyway, so I should have fun with this one.

**Comment by saulshanabrook** [comment]
Where should I put code/docs for this?

**Comment by cfregly** [comment]
@saulshanabrook here's the link to docker-stacks:  https://github.com/jupyter/docker-stacks

you can use that for now, then we'll plug in the PipelineIO-specific jupyter docker image.

**Comment by saulshanabrook** [comment]
@cfregly  I have it working with the tensorflow stack: https://github.com/fluxcapacitor/product/tree/master/jupterhub.
