### ISSUE TITLE
Monitor Spark job/task metrics with Prometheus

### ISSUE THREAD

**Issue by cfregly** [PipelineAI/pipeline#180]
http://rokroskar.github.io/monitoring-spark-on-hadoop-with-prometheus-and-grafana.html

https://argus-sec.com/monitoring-spark-prometheus/

**Comment by cfregly** [comment]
https://movio.co/blog/prometheus-service-discovery-kubernetes/

**Comment by matyix** [comment]
Hey @cfregly - fyi, we finally made the missing Spark sink to work with Prometheus - https://banzaicloud.com/blog/spark-monitoring/

**Comment by cfregly** [comment]
@matyix nice!  and given that @databricks needs something like this for their proprietary-notebook product, your chances of getting this committed are much higher!  :)

@felixcheung thanks for keeping an eye on this banzai PR.

**Comment by cfregly** [comment]
![image](https://user-images.githubusercontent.com/1438064/34162343-3813dfd8-e488-11e7-8360-827034689fe8.png)
