### ISSUE TITLE
KOPS Node & Master AMI - Investigate Possible Performance Improvements & GPU Support

### ISSUE THREAD

**Issue by BrentDorsey** [PipelineAI/pipeline#229]
On Apr 20, 2017, 11:32 PM -0400, Brent Dorsey <bdorsey@homeaway.com>, wrote:

[Ubuntu on AWS gets serious performance boost with AWS-tuned kernel](https://insights.ubuntu.com/2017/04/05/ubuntu-on-aws-gets-serious-performance-boost-with-aws-tuned-kernel/)
 
I wonder if it would be worth testing performance using an Ubuntu AMI?

I was thinking about the base AMI kops uses to build the kubernetes nodes (nodes & masters).  Currently I’m using:
         k8s-1.5-debian-jessie-amd64-hvm-ebs-2017-01-09

Brent Dorsey

From: Chris Fregly <chris@fregly.com>
Date: Friday, April 21, 2017 at 11:08 AM
To: Brent Dorsey <bdorsey@homeaway.com>
Subject: Re: Ubuntu on AWS gets serious performance boost with AWS-tuned kernel

gotcha.  yeah, i’m using the same k8s-1.5…-2017-10-09 thing.  i get nervous straying from that thing, but if we’re gonna support GPUs, i think we need to build a custom AMI anyway with the kubelet configured differently - or `docker` mapped to `nvidia-docker` or something.

**Comment by cfregly** [comment]
Deploying GPU Nodes on Kubernetes is a piece of cake, everything’s automated!  I don’t know what you were so worried about.  All you need is: 
 
 1.       k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02 
 2.       kubernetes-version 1.7.0-alpha.4 
 3.       kubernetes Accelerators=true featureGate 
 4.       kops version 1.6.0 
 5.       kops kopeio/nvidia-bootstrap:1.6 gpu hook 
 
```
... 
   hooks: 
   - execContainer: 
       image: kopeio/nvidia-bootstrap:1.6 
...
 kubelet: 
     featureGates: 
       Accelerators: "true" 
...
```

**Comment by cfregly** [comment]
disable autoboost feature of Nvidia driver and set the GPU clock speed to max frequency per 

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/optimize_gpu.html

**Comment by cfregly** [comment]
Follow these instructions on AWS:   http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html

**Comment by cfregly** [comment]
https://github.com/NVIDIA/k8s-device-plugin

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/device-plugin.md

https://github.com/NVIDIA/nvidia-docker (v2.0)

**Comment by cfregly** [comment]
using appropriate AMIs from Nvidia/AWS for optimized GPU experience
