### ISSUE TITLE
Add Python 2.7 Support to PipelineAI CLI

### ISSUE THREAD

**Issue by cfregly** [PipelineAI/pipeline#236]
Currently Only Python 3+

**Comment by cfregly** [comment]
- build 1 compatibility project to hide all of this complexity
- use the six project `if six.py2: ...`
- use from __future__, etc.
- can't use type annotations like `(arg:bytes) -> bytes`
- concurrency / threading will need to change

**Comment by BrentDorsey** [comment]
what's driving the need to support Python 2.7?

**Comment by cfregly** [comment]
completed
