### ISSUE TITLE
Working example of incorporating AOT with Pb graph?

### ISSUE THREAD

**Issue by kwotsin** [PipelineAI/pipeline#246]
Is there a working example showing how AOT could compile a PB graph for use in android devices? I came to your repository following this slideshare: https://www.slideshare.net/Hadoop_Summit/optimizing-profiling-and-deploying-high-performance-spark-ml-and-tensorflow-ai-models-in-production-with-gpus

I find the possibility of compiling an optimized graph with AOT rather exciting - is there a way to do this?

**Comment by cfregly** [comment]
@kwotsin we haven't yet exposed a public version of this AOT functionality.  I'll try to prioritize this for a near-term release as we have working code, but it's specific to one of our customers.

thanks for the issue.  keeping this open for tracking purposes.

**Comment by kwotsin** [comment]
@cfregly Thanks for mentioning this! Great to hear that you have something working with AOT - how did you find the performance for AOT so far in terms of speed/accuracy/memory consumption (if you could share)?

**Comment by cfregly** [comment]
Relevant links:

- https://stackoverflow.com/questions/46556553/cannot-create-the-final-binary-using-tensorflow-aot-compilation-for-cpu-backend
- https://github.com/tensorflow/tensorflow/issues/13482
- https://github.com/tensorflow/tensorflow/issues/13500

**Comment by cfregly** [comment]
related to TensorFlow Lite:  https://www.tensorflow.org/mobile/tflite/
