### ISSUE TITLE
Add TensorFlow Dataset API Support 

### ISSUE THREAD

**Issue by cfregly** [PipelineAI/pipeline#251]
https://www.tensorflow.org/programmers_guide/datasets

**Comment by cfregly** [comment]
keep an eye on tf.Transform:  https://github.com/tensorflow/transform/

Apache Beam is first impl of this batch-ingestion pattern.

**Comment by eggie5** [comment]
Datasets works great for training, however, as far as I can tell currently it's not compatible w/ TF Serving. For example, the "initializable" example from this page https://www.tensorflow.org/programmers_guide/datasets#creating_an_iterator cannot be run w/ Serving b/c there's no way to run the equivalent of this line:

```
sess.run(iterator.initializer, feed_dict={max_value: 10})
```

In serving you can run the initializer using the `legacy_init_op` argument to the builder however, you can't do it after the tensor is set as in the feed_dict example above.

I saw this commit a few days ago: https://github.com/tensorflow/tensorflow/commit/fb180d58d16f1b63a6f714593c58bbd8978bb4a3#diff-bcc45247a86293d0e831151ea7c2619f

Which may be the fix as it allows you to use the Dataset pipeline w/o the init step. Testing it now by building Serving from source...

**Comment by cfregly** [comment]
@eggie5 did you make any progress on this?  curious what you found re: TF Serving + Datasets.
