### ISSUE TITLE
Pipeline CLI improvements

### ISSUE THREAD

**Issue by cfregly** [PipelineAI/pipeline#255]
currently, tracebacks do not provide enough info.

also, --model-version=1.0 fails as the "1.0" is a treated as a float.

lastly, --help isn't very easy to use.

**Comment by BrentDorsey** [comment]
I have some ideas for this, google's python-fire swallows a lot of exception feedback.

Locally I'm using fire's FireError function to raise errors and I'm about to subclass FireError so I can log stack traces when debug is enabled.

**Comment by BrentDorsey** [comment]
Below is what I'm currently using.  I'm going to subclass FireError.
` except Exception as exc:
    raise FireError('PipelineCli.<methodName> {} Exception: {}'.format(msg, str(exc)))`
