### ISSUE TITLE
TensorFlow example model doesn't start

### ISSUE THREAD

**Issue by AndriiNeverov** [PipelineAI/pipeline#256]
Running

pipeline model-build --model-type=tensorflow --model-name=mnist --model-tag=master --model-path=./models/tensorflow/mnist

pipeline model-start --model-type=tensorflow --model-name=mnist --model-tag=master --memory-limit=2G

pipeline model-logs --model-type=tensorflow --model-name=mnist --model-tag=master

reveals at least two issues:

1) 

Starting JVM-based Dashboard Server...

Error: Unable to access jarfile /root/jetty-0.4.7.RC0.jar

2) Introduced by 54d68bbcad76879ff660c3511f19e003454c16b0:

 * Starting nginx nginx                                                  [ OK ]
./run: line 190: x: command not found

**Comment by cfregly** [comment]
fixing right now!

**Comment by cfregly** [comment]
ok, this should all be fixed.  reopen if there is still an issue.

**Comment by cfregly** [comment]
the ticket seems to have disappeared?!

—

Chris Fregly
Founder and CEO @ PipelineAI <http://pipeline.io/>
Organizer @ Advanced Spark and TensorFlow Meetup <http://www.meetup.com/Advanced-Spark-and-TensorFlow-Meetup>
San Francisco - Chicago - Washington DC - London

**Comment by stupidfakeaccount** [comment]
Hi Chris,

I’m experiencing the same issue as the one referenced above. I cannot connect to local host:6969 when following the api documentation on Ubuntu 16.04.3. I’ve tried rebuilding and following a demo video I found on your site but the issue persists. Some services like Prometheus and Graphsna come up, but that’s it.

**Comment by cfregly** [comment]
@stupidfakeaccount i made a change to the code and documentation this weekend that *should* fix your issue.

Follow these instructions with the latest `cli-pipeline==1.2.28` and let me know if you're still having issues:  https://github.com/PipelineAI/predict

If you're still having issues, please paste the full container logs here - and use `model-shell` to shell into the running container to capture the results of the running processes with `ps -aef`.

Thanks!

-Chris

**Comment by cfregly** [comment]
@stupidfakeaccount  assuming this works now?

we've released v1.3.0, btw:  https://github.com/PipelineAI/predict/tree/v1.3.0
