### ISSUE TITLE
pipeline predict-model doesn't work

### ISSUE THREAD

**Issue by ddaue** [PipelineAI/pipeline#258]
pipeline predict-model --model-type=tensorflow --model-name=mnist --model-tag=v1 --predict-server-url=http://localhost:6969 --test-request-path=./models/tensorflow/mnist/data/test_request.json
Fire trace:
1. Initial component
2. Instantiated class "PipelineCli" (/usr/local/lib/python3.5/dist-packages/cli_pipeline/__init__.py:23)
3. ('Could not consume arg:', 'predict-model')
Type:        PipelineCli
String form: <cli_pipeline.__init__.PipelineCli object at 0x7f0ab7411cc0>
File:        /usr/local/lib/python3.5/dist-packages/cli_pipeline/__init__.py
Usage:       pipeline 
             pipeline cluster-connect
             pipeline cluster-describe
             pipeline cluster-logs
             pipeline cluster-quarantine
             pipeline cluster-rollback
             pipeline cluster-rollout
             pipeline cluster-scale
             pipeline cluster-shell
             pipeline cluster-start
             pipeline cluster-status
             pipeline cluster-stop
             pipeline cluster-train
             pipeline optimizer-generate
             pipeline prediction-loadtest
             pipeline prediction-test
             pipeline server-build
             pipeline server-logs
             pipeline server-pull
             pipeline server-push
             pipeline server-shell
             pipeline server-start
             pipeline server-stop
             pipeline server-train
             pipeline traffic-deregister
             pipeline traffic-describe
             pipeline traffic-register
             pipeline traffic-shadow
             pipeline traffic-split
             pipeline traffic-status
             pipeline version

Thanks !

**Comment by cfregly** [comment]
@ddaue can you run `pipeline version` and paste the results here?

the most-stable release is here, btw:  https://github.com/PipelineAI/predict/tree/v1.3.0

and you need to be using cli-pipeline==1.3.0 per this link:  https://github.com/PipelineAI/predict/tree/v1.3.0#install-pipelinecli

we'll be releasing 1.4.0 soon with an updated cli-pipeline, but this should get you going for now.

thanks!
