### ISSUE TITLE
Setup Pipeline on Docker Swarm?

### ISSUE THREAD

**Issue by MarsWarrior** [PipelineAI/pipeline#263]
Newbe here ;-)

Since PipelineAI is using Docker containers, I assume that these can be run inside a Docker Swarm.
However, I can't find any clues or documentation about this.

Could anyone from the PipelineAI team elaborate on this?

Currently using Docker Swarm and [OpenFaaS](https://github.com/openfaas/faas).
It would be very nice if we can fully integrate PipelineAI into this environment & toolset.

**Comment by cfregly** [comment]
which part of PipelineAI are you interested in?  feature engineering/etl?  model training?  model serving?

**Comment by MarsWarrior** [comment]
Good Question.

The Docker Swarm cluster is for production. So model serving would be the primary goal I guess.

Developers have there own VM with Docker on their development PC, so for the minimal setup they would use that environment for feature engineering/etl and model training.
In the long run I would prefer that those two would also run on a Swarm  using jupyterhub.

As I just discovered PipelineAI, it is not yet clear to me how to setup/use the Standalone version and integrate that in our current Docker Swarm platform and Dockerized development environment. The main goal is using PipelineAI for streaming analytics.

**Background info:**

- We use Prometheus/Grafana for metrics. OpenFaas uses that too for automatic scaling.
- Current ML/AI solutions are using jupyter and Tensorflow in a Docker container. I want to 'upgrade' the current solution to - if possible - PipelineAI.
- Current ML/AI solutions don't use a GPU. That is also a future goal: add hardware to the Docker Swarm cluster to support Tensorflow GPU deployments.
- Main focus is on Tensorflow, but we also have a Hadoop cluster, where Spark ML is not yet used a lot. SciKit, R and Numpy are also used. It seems that PipelineAI can integrate them all, which is a big plus.

**Comment by MarsWarrior** [comment]
Hi Chris, A Happy 2018!

Any update on the Docker Swarm question?

Thanx!

**Comment by cfregly** [comment]
@MarsWarrior join our public [slack channel](https://join.slack.com/t/pipelineai/shared_invite/enQtMjg3MTYzNjg1OTY5LWQxM2E5MDFhYTAzMDdkYmU2NjEyMmIxYTg5MjcyZGE3N2JiMWM4OWQxMzI2NzVlNTk3Y2JlMjQ1MWM3M2M0Mjc) to discuss offline.  we can summarize back here.

talk soon!

**Comment by alexellis** [comment]
Would like to know more about the use of OpenFaaS. thanks 👍

**Comment by MarsWarrior** [comment]
@cfregly Haven't had time yet to talk on slack. Just registered. Due to the time difference and a very busy time at work. However we managed to get some of PipelineAI to work on Docker Swarm: multiple & scalable TensorServe containers including A/B testing with weights! Nothing dynamic yet, but already very usable for our purpose :yum:

Hope to talk on Slack soon!

@alexellis Nice found this thread Alex! Google Analytics or just by coincidence?

We are currently exploring OpenFaaS possibilities in conjuction with AI to serve models as a service: a raspberry pi or even simpler hardware like an ESP32 for instance can call a model (including data as JSON) through OpenFaaS.

Other possibilities like publishing to an MQTT topic which triggers an OpenFaaS function is also on our agenda. In that way we can 'authorize' specific devices and topics to 'call' OpenFaaS functions, and thus everything OpenFaaS can call such as AI models.

We might need some extra functionality in OpenFaas to accomplish this all, but that's something I currently don't know yet. You will find them on the OpenFaaS issue list once we get there :relaxed:
Autoscaling containers based on CPU time would be very nice...

**Comment by cfregly** [comment]
@MarsWarrior awesome!  yeah, our PipelineAI Docker containers can run anywhere.  does Docker Swarm support weight-based load balancing?  last i checked, it didn't.

and funny enough, i heard about OpenFaaS from this github issue.  so thank you!  i reached out to alex earlier today to join their slack channel.  

we're currently integrating OpenFaaS into PipelineAI.  woot!

**Comment by dougzhang** [comment]
How does PipelineAI compare to datmo ?


Sent by Douglas Z

On Jan 18, 2018, at 16:23, Chris Fregly <notifications@github.com<mailto:notifications@github.com>> wrote:


@MarsWarrior<https://github.com/marswarrior> awesome! yeah, our PipelineAI Docker containers can run anywhere. does Docker Swarm support weight-based load balancing? last i checked, it didn't.

and funny enough, i heard about OpenFaaS from this github issue. so thank you! i reached out to alex earlier today to join their slack channel.

we're currently integrating OpenFaaS into PipelineAI. woot!

**Comment by MarsWarrior** [comment]
> @MarsWarrior awesome! yeah, our PipelineAI Docker containers can run anywhere. does Docker Swarm support weight-based load balancing? last i checked, it didn't.

No Docker Swarm Mode doesn't support that, but [Traefik](https://traefik.io/) does as a Swarm aware http proxy/loadbalancer!

> and funny enough, i heard about OpenFaaS from this github issue. so thank you! i reached out to alex earlier today to join their slack channel.

That is indeed funny, and very nice to here that you see possibilities!
And now I understand how Alex 'found' this issue.

> we're  currently integrating OpenFaaS into PipelineAI. woot!

More awesome news. What are you planning to integrate with @alexellis work?

And as of today, one awesome dev managed to get the model metrics working in Docker Swarm Mode after digging through the PipelineAI code wondering why that didn't 'just work' :grin:

**Comment by cfregly** [comment]
@MarsWarrior any feedback on how to make the PipelineAI model metrics "just work"?  can you connect me with the dev on our Slack channel [here](https://join.slack.com/t/pipelineai/shared_invite/enQtMjg3MTYzNjg1OTY5LWQxM2E5MDFhYTAzMDdkYmU2NjEyMmIxYTg5MjcyZGE3N2JiMWM4OWQxMzI2NzVlNTk3Y2JlMjQ1MWM3M2M0Mjc)?

**Comment by cfregly** [comment]
gotcha re: swarm + traefik.  we started with traefik, but moved to istio for the circuit breaker capabilities - and first-class kube integration, of course.

we've already integrated the OpenFaaS stuff.  our designs were very similar, so this ended up being a simple task of adding labels to our Kubernetes objects.  this is all we needed to work with @alexellis OpenFaaS.

i'll have a slick demo to present at the next #FaasFriday (tomorrow?!)

**Comment by MarsWarrior** [comment]
@cfregly I will ask. He subscribed to this issue, so probably already read your request.

We are on Amsterdam time (currently almost 11 o'clock in the evening). Your comment was 2 hours ago, so in which timezone are you?

Curious about your slick demo of course!

**Comment by cfregly** [comment]
@MarsWarrior was able to deploy the Docker images on Docker Swarm.
