### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rizplate** [PipelineAI/pipeline#267]
I am trying to get some understanding of the Pipeline.AI, but I can not find any documentation.

Can someone please point me to the documentation?

**Comment by cfregly** [comment]
We feel that the best documentation is hands-on documentation, so here is our latest PipeilneAI Quick Start for Docker, Kubernetes, AWS SakeMaker, OpenFaaS Serverless Functions:  https://github.com/PipelineAI/pipeline/tree/master/docs/quickstart/  

Also, here is our live, PipelineAI GPU Community Edition:  http://community.pipeline.ai

You can train, optimize, deploy, and consume your own models using all popular ML and AI frameworks including Scikit-Learn, TensorFlow, PyTorch, Caffe - or even just straight-up Python and Java!

Click [**HERE**](https://join.slack.com/t/pipelineai/shared_invite/enQtMjg3MTYzNjg1OTY5LWQxM2E5MDFhYTAzMDdkYmU2NjEyMmIxYTg5MjcyZGE3N2JiMWM4OWQxMzI2NzVlNTk3Y2JlMjQ1MWM3M2M0Mjc) to join us on Slack for more interactive question-answering.

Hope that helps!

**Comment by alexellis** [comment]
Hey @cfregly how is this going?

**Comment by cfregly** [comment]
@alexellis hey alex!  whatcha looking for?
