### ISSUE TITLE
Keras/linear model prediction error

### ISSUE THREAD

**Issue by umar-sik** [PipelineAI/pipeline#270]
Hi, 

When I try to predict with **pipeline predict-kube-test --model-name=linear --test-request-path=./keras/linear/input/predict/test_request.json --test-request-concurrency=10**, I get 
ModelPredictPython3Handler.post: Exception - '
 "linear/a/keras/python/cpu Error 'NoneType' object has no attribute.
What could be the problem here? 

P.S the mnist prediction is working fine.

**Comment by cfregly** [comment]
@umar-sik is this still an issue?  i believe we fixed this last week, correct?

**Comment by umar-sik** [comment]
Yes we did. Thanks again.
