### ISSUE TITLE
Error loading prometheus configuration

### ISSUE THREAD

**Issue by Bragegs** [PipelineAI/pipeline#271]
Python==3.6.3
cli-pipeline==1.5.101 

**Error:**
Following tutorial in quickstart/docker. Something wrong with loading  prometheus image.

**Command:**
 ```pipeline predict-server-start --model-name=mnist --model-tag=cpu --memory-limit=2G``` 

**Output from predict-server-logs:**
> ...
> level=info ts=2018-04-06T13:51:57.521218915Z caller=main.go:520 msg="TSDB started"
> level=info ts=2018-04-06T13:51:57.521287397Z caller=main.go:596 msg="Loading configuration file" filename=/root/prometheus-2.2.0-rc.1.linux-amd64/prometheus.yml
> level=info ts=2018-04-06T13:51:57.521854084Z caller=main.go:398 msg="Stopping scrape discovery manager..."
> level=info ts=2018-04-06T13:51:57.521906121Z caller=main.go:411 msg="Stopping notify discovery manager..."
> level=info ts=2018-04-06T13:51:57.521941824Z caller=main.go:435 msg="Stopping scrape manager..."
> level=info ts=2018-04-06T13:51:57.522067041Z caller=manager.go:460 component="rule manager" msg="Stopping rule manager..."
> level=info ts=2018-04-06T13:51:57.522347173Z caller=manager.go:466 component="rule manager" msg="Rule manager stopped"
> level=info ts=2018-04-06T13:51:57.522194851Z caller=main.go:394 msg="Scrape discovery manager stopped"
> level=info ts=2018-04-06T13:51:57.522290467Z caller=main.go:407 msg="Notify discovery manager stopped"
> level=info ts=2018-04-06T13:51:57.522230227Z caller=main.go:429 msg="Scrape manager stopped"
> level=info ts=2018-04-06T13:51:57.522537438Z caller=notifier.go:512 component=notifier msg="Stopping notification manager..."
> level=info ts=2018-04-06T13:51:57.522696518Z caller=main.go:581 msg="Notifier manager stopped"
> level=error ts=2018-04-06T13:51:57.52278673Z caller=main.go:590 err="Error loading config couldn't load configuration (--config.file=/root/prometheus-2.2.0-rc.1.linux-amd64/prometheus.yml): parsing YAML file /root/prometheus-2.2.0-rc.1.linux-amd64/prometheus.yml: yaml: line 11: did not find expected key"
> level=info ts=2018-04-06T13:51:57.522858478Z caller=main.go:592 msg="See you next time!"
> ...

**Side effect:**
Trying to create a data source in Grafana causes error with Prometheus empty response.

![screen shot 2018-04-06 at 17 06 53](https://user-images.githubusercontent.com/10655264/38429207-0bc3d844-39be-11e8-93c2-5aa093cb2d63.png)

**Comment by cfregly** [comment]
@BrentDorsey can you take this?

**Comment by BrentDorsey** [comment]
@cfregly - yes, researching...

**Comment by cfregly** [comment]
@Bragegs try it now.  

we actually upgraded both prometheus and grafana, as well.  you might want to upgrade to `cli-pipeline==1.5.103`.  it's not required, but recommended.

and we threw in a huge performance improvement, as well, on the prediction path.  we're seeing 200% improvement on request/response times for the tensorflow models.  combination of a few things.

let us know if you have any issues.  you can also ping us on [slack](https://slack.pipeline.ai), as well.

keep the feedback coming!!
