### ISSUE TITLE
Pipeline CLI on Windows with PowerShell causes `docker: invalid reference format` error

### ISSUE THREAD

**Issue by cfregly** [PipelineAI/pipeline#272]
```
### Pipeline CLI Command
"pipeline train-server-start --model-name=mnist --model-tag=cpu --input-host-path=./tensorflow/mnist-cpu/input/ --output-host-path=./tensorflow/mnist-cpu/model/pipeline_tfserving/ --train-args="--train-epochs=2 --batch-size=100""
```
```
### Output
docker run -itd -p 2222:2222 -p 6006:6006 -e PIPELINE_LOCAL_MODEL=true -e PIPELINE_STREAM_LOGGER_URL=None -e PIPELINE_STREAM_LOGGER_TOPIC=None -e PIPELINE_STREAM_INPUT_URL=None -e PIPELINE_STREAM_INPUT_TOPIC=None -e PIPELINE_STREAM_OUTPUT_URL=None -e PIPELINE_STREAM_OUTPUT_TOPIC=None -e TF_CONFIG='{"environment": "local", "task":{"type": "worker"}}' -e PIPELINE_TRAIN_ARGS="--train-epochs=2 --batch-size=100" -v c:\programdata\anaconda3\lib\site-packages\cli_pipeline:/opt/ml/input/samples/models/ -v C:\Users\Frioui\Desktop\pipelineAI\models\tensorflow\mnist-cpu\input:/opt/ml/input/ -v C:\Users\Frioui\Desktop\pipelineAI\models\tensorflow\mnist-cpu\model:/opt/ml/output/ --name=train-mnist-cpu -m 2G docker.io/pipelineai/train-mnist:cpu train
```
```
###  Error
docker: invalid reference format.

See 'docker run --help'.

container name: 'train-mnist-cpu'
```

**Comment by naoufelfrioui** [comment]
![wieder problem](https://user-images.githubusercontent.com/23002236/38471330-dc0f9fbc-3b6f-11e8-884e-da9590cf5a1b.PNG)


I used \ but the same problem

**Comment by cfregly** [comment]
@naoufelfrioui can you try to massage that "docker run..." command until it works?

we're outputting that `docker` command for debugging purposes.

in other words, let's try to narrow down where the issue is by simplifying that docker command and identifying exactly where it breaks. 

`train-server-start` only **requires** 2 args:  `model-name` and `model-tag` - but you'll need to pass in more args for the training to be useful, of course.

**Comment by cfregly** [comment]
the problem is with the actual docker command, of course.  so let's narrow that down and we'll fix it right away.

**Comment by cfregly** [comment]
*the args passed to the docker command, that is.

**Comment by naoufelfrioui** [comment]
I have already tested docker with a simple example. it works without problem

**Comment by wittfabian** [comment]
Has this bug been fixed?
I still get the error with cmd.exe.
