### ISSUE TITLE
Windows and \ in Dockerfile

### ISSUE THREAD

**Issue by robnoflop** [PipelineAI/pipeline#274]
Hi, I ran into some problems using docker Scikit-Learn example on Windows. Maybe the solution I found can help you to narrow down this problem. 

### Windows-Specification:
Edition: windows 10 pro
Version: 1709
OSbuild: 16299.492

### Docker 
Version: 18.03.1-cd-win65 (17513)

### pipeline version
_models_base_path: C:\Users\\{user}\repos\models
['C:\\Users\\\{user}\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\pipeline', 'version']

CLI version: 1.5.171
API version: v1

Default build type: docker
Default build context path: . => C:\Users\\{user}\repos\models

Default train base image: docker.io/pipelineai/train-cpu:1.5.0
Default predict base image: docker.io/pipelineai/predict-cpu:1.5.0

cli_version:                1.5.171
api_version:                v1
build_type_default:         docker
build_context_path:         C:\Users\\{user}\repos\models
build_context_path_default: .
train_base_image_default:   docker.io/pipelineai/train-cpu:1.5.0
predict_base_image_default: docker.io/pipelineai/predict-cpu:1.5.0

## The Problem
The command "pipeline train-server-build" produces the following error.
COPY failed: stat /var/lib/docker/tmp/docker-builder850613725/scikitmnistmodel/pipeline_setup.sh: no such file or directory

In the gengerated dockerfile the copy command was generated as follow
COPY scikit\mnist\model/pipeline_setup.sh $PIPELINE_MODEL_PATH/pipeline_setup.sh

I changed it to
COPY scikit/mnist/model/pipeline_setup.sh $PIPELINE_MODEL_PATH/pipeline_setup.sh
and just ran docker build and the error moved to the next copy command.

### Train

1. pipeline train-server-build --model-name=mnist --model-tag=v1 --model-type=scikit --model-path=./scikit/mnist/model
3.  modify docker file -> changing \ to / in all COPY commands change PIPELINE_MODEL_PATH to /opt/ml/output
6. check if pipeline_setup.sh has only LF and not CRLF
3. docker build . -f .pipeline-generated-train-mnist-v1-Dockerfile -t pipelineai/train-mnist:v1
4. docker run -itd -p 2222:2222 -p 6006:6006 -e PIPELINE_SINGLE_SERVER_ONLY=true -e PIPELINE_STREAM_LOGGER_URL=None -e PIPELINE_STREAM_LOGGER_TOPIC=None -e PIPELINE_STREAM_INPUT_URL=None -e PIPELINE_STREAM_INPUT_TOPIC=None -e PIPELINE_STREAM_OUTPUT_URL=None -e PIPELINE_STREAM_OUTPUT_TOPIC=None -e TF_CONFIG='{"environment": "local", "task":{"type": "worker"}}' -e PIPELINE_TRAIN_ARGS="" -v C:\Users\\{user}\repos\models\scikit\mnist\input:/opt/ml/input/ -v C:\Users\\{user}\repos\models\scikit\mnist\model:/opt/ml/output/ -v C:\Users\\{user}\repos\models\scikit\mnist\model:/root/pipelineai/training_runs/ --name=train-mnist-v1  --shm-size=512m docker.io/pipelineai/train-mnist:v1 train

### Deploy

1. pipeline predict-server-build --model-name=mnist --model-tag=v1 --model-type=scikit --model-path=./scikit/mnist/model/
2. modify docker file -> changing \ to / in all COPY commands
3. docker build . -f .pipeline-generated-predict-mnist-v1-scikit-python-cpu-Dockerfile -t pipelineai/predict-mnist:v1
4. check if pipeline_modelserver.properties has only LF and not CRLF
5. pipeline predict-server-start --model-name=mnist --model-tag=v1

**Comment by cfregly** [comment]
@robnoflop any chance you can use PowerShell to get around the `\` `/` situation?
