### ISSUE TITLE
Uploading Model to PipelineAI throws exception

### ISSUE THREAD

**Issue by kaiwaehner** [PipelineAI/pipeline#278]
Not sure if other Python packages need to be updated. Or if the syntax of my command is not correct.

After installing pipeline CLI successfully and being in the 'model' folder, tried:

pipeline resource-upload --host community.cloud.pipeline.ai --user-id XYZ --resource-type model --resource-subtype tensorflow  --name tensorflow-mnist-v3 --tag tensorflow-mnist-v3-version-1 --path ./tensorflow/mnist-v3/model

pipeline resource-upload --host community.cloud.pipeline.ai --user-id "XYZ" --resource-type model --resource-subtype tensorflow  --name "tensorflow-mnist-v3" --tag "tensorflow-mnist-v3-version-1" --path ./tensorflow/mnist-v3/model

I assume the syntax is correct. But a concrete example in the docs would be good in addition to the abstract version: 

pipeline resource-upload --host community.cloud.pipeline.ai --user-id <YOUR_USER_ID> --resource-type model --resource-subtype tensorflow  --name <YOUR_MODEL_NAME> --tag <YOUR_TAG_NAME> --path ./tensorflow/mnist-v3/model

Also, I am not 100% sure what value <YOUR_MODEL_NAME> and <YOUR_TAG_NAME> can have... Is it anything I define? So it just needs to be unique for my user-id and a String? Or any other limitations / requirements? 

In both cases, I get the following exception when trying to upload a model:

kai.waehner@Kais-MacBook-12:~/git-projects/models|master
⇒  pipeline resource-upload --host community.cloud.pipeline.ai --user-id "93dcf122" --resource-type model --resource-subtype tensorflow  --name "tensorflow-mnist-v3" --tag "tensorflow-mnist-v3-version-1" --path ./tensorflow/mnist-v3/model
['/Users/kai.waehner/anaconda2/envs/PipelineAI/bin/pipeline', 'resource-upload', '--host', 'community.cloud.pipeline.ai', '--user-id', '93dcf122', '--resource-type', 'model', '--resource-subtype', 'tensorflow', '--name', 'tensorflow-mnist-v3', '--tag', 'tensorflow-mnist-v3-version-1', '--path', './tensorflow/mnist-v3/model']

...Started

Packaging New Resource for PipelineAI...
Traceback (most recent call last):
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/bin/pipeline", line 11, in <module>
    sys.exit(_main())
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/cli_pipeline/cli_pipeline.py", line 5269, in _main
    _fire.Fire()
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/cli_pipeline/cli_pipeline.py", line 1340, in resource_upload
    name, tag, absolute_path, exclude_file_list=exclude_file_list
  File "/Users/kai.waehner/anaconda2/envs/PipelineAI/lib/python3.7/site-packages/cli_pipeline/cli_pipeline.py", line 2580, in model_archive_tar
    tar.add(model_path, arcname=_model_subdir_name, exclude=exclude, filter=_filter_tar)
TypeError: add() got an unexpected keyword argument 'exclude'

**Comment by cfregly** [comment]
hey @kaiwaehner !

this is likely related to the Python 3.7 issue you discovered recently (#277).

working on a fix.  thanks for reporting

**Comment by cfregly** [comment]
@kaiwaehner ok, we fixed the issue.  the new cli is [1.5.213](https://github.com/PipelineAI/pipeline/blob/master/docs/quickstart/README.md)
