### ISSUE TITLE
Istio 1.0

### ISSUE THREAD

**Issue by ericwangqing** [PipelineAI/pipeline#281]
Istio has already been in 1.0. Will PipelinAI step forward to it? Is there any plan?

**Comment by cfregly** [comment]
@ericwangqing have you tried converting the PipelineAI-generated istio.yaml to the new Istio 1.0 gateway-based networking?

if so, can you share an example with us?  we'd like to validate our generated templates.

**Comment by cfregly** [comment]
upgraded to 1.0
