### ISSUE TITLE
Could not find conda environment: train

### ISSUE THREAD

**Issue by un-knight** [PipelineAI/pipeline#283]
I follow the [tutorial](https://github.com/PipelineAI/pipeline/blob/master/docs/quickstart/docker/README-training.md#train-a-pytorch-model) to build pytorch training server. But there are some environmental problems with the container.
![image2018-9-13_13-45-34](https://user-images.githubusercontent.com/8266614/45478138-d5279d80-b775-11e8-9ea8-cc7a3dc00a62.png)
As the logs shown, there are two issues with the container:
1. could not find environment: train
2. could not open file `/pipeline_train.py`

Then, I enter the container using the command `pipeline train-server-shell` and find that:
1. conda environment name is `pipeline-train`
2. `pipeline_train.py` locates in `/root/`

Does anybody have ideas to fix this?

**Comment by ericwangqing** [comment]
It seems that the conda environment wan't configured properly. Did you get any warning when build the train image about conda's environment settings? You may check the conda environment in your train pod by 
```bash
kubectl exec -it <your-train-pod> -- /bin/bash
$you-pod:~# conda env list
```

**Comment by cfregly** [comment]
@un-knight 

ok, this is now fixed.  make sure you do the following:

`pipeline env_registry_sync --tag=1.5.0`

then re-run the training steps here:

https://github.com/PipelineAI/pipeline/blob/master/docs/quickstart/docker/README-training.md

thanks @ericwangqing for your input.  

we renamed those variables to PIPELINE_RESOURCE_* from PIPELINE_MODEL_*, but the Docker image wasn't yet pushed.

thanks for helping us track this down.  please re-open if there is still an issue.  we've updated the docs, as well, to fix some minor typos.
