### ISSUE TITLE
How to develop application log analytics tool using Deep-learning 

### ISSUE THREAD

**Issue by paulsuk1982** [PipelineAI/pipeline#285]
Hello All,

I am hoping Chris is doing well, I attended 2 or 3 of his sessions in Deploying Tensor Flow in Production, it was nicely organized and having deep technical understanding and hands on.

could you please give an idea or though process how to develop a machine learning model on application Log or sensor Data using Tensor Flow or SciKit learn so anomalies can be detected on proactive basis.

**Comment by cfregly** [comment]
@paulsuk1982 let's discuss this offline.  find me on slack - and we can discuss the details.

https://joinslack.pipeline.ai
