### ISSUE TITLE
Failed start Spring in Docker container

### ISSUE THREAD

**Issue by deadman2000** [PipelineAI/pipeline#287]
I'm trying to start PipelineAI on Windows 7 host with Docker on VirtualBox.

```
pipeline env-registry-sync --tag=1.5.0
pipeline predict-server-build --model-name=mnist --model-tag=v1tensorflow --model-type=tensorflow --model-runtime=python --model-path=./tensorflow/mnist-v1/model
pipeline predict-server-start --model-name=mnist --model-tag=v1tensorflow --memory-limit=2G
pipeline predict-server-logs --model-name=mnist --model-tag=v1tensorflow
```

Starting failed on Spring with exception:
```
java.lang.NumberFormatException: For input string: "5000
"
```

I think, problem in breakline after 5000.

Full log: [crash.log](https://github.com/PipelineAI/pipeline/files/2519183/crash.log)

**Comment by deadman2000** [comment]
@cfregly yes. same exception.

Log: [pshell.log](https://github.com/PipelineAI/pipeline/files/2603631/pshell.log)

**Comment by cfregly** [comment]
@deadman2000 we're still debugging this.  we're making changes to our base images, so we're combining these efforts.

one thing i noticed is that you're passing `--memory-limit=2G`.  we've changed this to `--predict-memory-limit=2G`.

i'll make sure the samples reflect this.

we're still seeing an error upon startup, so we're debugging this now, as well.  more to come...  thanks for your help!
