### ISSUE TITLE
tensorflow_kafka_test.py does not work

### ISSUE THREAD

**Issue by Lihengwannafly** [PipelineAI/pipeline#290]
I want to read the stream data to feed into my model, then I find _tensorflow_kafka_test.py_. But when I copy the imports and find that tensorflow.contrib.kafka does not exist.
```
from tensorflow.contrib.kafka.python.ops import kafka_dataset_ops
from tensorflow.python.data.ops import iterator_ops
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import errors
from tensorflow.python.ops import array_ops
from tensorflow.python.platform import test
```

**Comment by cfregly** [comment]
Which version of TensorFlow are you using?

TF 1.13+ is removing the contrib package.

We’re working on this code right now, actually.
