### ISSUE TITLE
[question] This Slack invite link is no longer active.

### ISSUE THREAD

**Issue by gaocegege** [PipelineAI/pipeline#296]
https://pipelineai.slack.com/join/shared_invite/enQtMjg3MTYzNjg1OTY5LWQxM2E5MDFhYTAzMDdkYmU2NjEyMmIxYTg5MjcyZGE3N2JiMWM4OWQxMzI2NzVlNTk3Y2JlMjQ1MWM3M2M0Mjc cannot be used now.

**Comment by cfregly** [comment]
https://joinslack.pipeline.ai has been updated.
